export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const UPDATE_CUSTOMER_NAME = "UPDATE_CUSTOMER_NAME";
export const UPDATE_CUSTOMER_EMAIL = "UPDATE_CUSTOMER_EMAIL";
export const UPDATE_CUSTOMER_PHONE = "UPDATE_CUSTOMER_PHONE";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";